
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaapplication3.Student;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Acer
 */
public class interface1 extends javax.swing.JFrame {

    /**
     * Creates new form interface1
     */
    public interface1() {
        initComponents();
        this.setLocationRelativeTo(null);
        Tb_student("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPv = new javax.swing.JLabel();
        jM = new javax.swing.JLabel();
        jBD1 = new javax.swing.JLabel();
        jFN = new javax.swing.JLabel();
        jLN = new javax.swing.JLabel();
        jOK = new javax.swing.JButton();
        jCancel = new javax.swing.JButton();
        jDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_student = new javax.swing.JTable();
        jID_Student = new javax.swing.JLabel();
        jB = new javax.swing.JLabel();
        jDt = new javax.swing.JTextField();
        jID_Class = new javax.swing.JLabel();
        jPama = new javax.swing.JLabel();
        jpassword1 = new javax.swing.JTextField();
        search = new javax.swing.JTextField();
        jLname = new javax.swing.JTextField();
        jVillage = new javax.swing.JTextField();
        jprovine = new javax.swing.JTextField();
        jlevel = new javax.swing.JTextField();
        jparent = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Fname1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jDateChoose = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.pink);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 153, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPv.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        jPv.setText("ແຂວງ:");
        jPanel1.add(jPv, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        jM.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        jM.setText("ເມືອງ:");
        jPanel1.add(jM, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jBD1.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        jBD1.setText("ວດປ ເກີດ :");
        jPanel1.add(jBD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jFN.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        jFN.setText("ຊື່  :");
        jPanel1.add(jFN, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jLN.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        jLN.setText("ນາມສະກຸນ :");
        jPanel1.add(jLN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jOK.setFont(new java.awt.Font("Phetsarath OT", 0, 11)); // NOI18N
        jOK.setText("ADD");
        jOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOKActionPerformed(evt);
            }
        });
        jPanel1.add(jOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 64, -1));

        jCancel.setFont(new java.awt.Font("Phetsarath OT", 0, 11)); // NOI18N
        jCancel.setText("Cancel");
        jCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelActionPerformed(evt);
            }
        });
        jPanel1.add(jCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, -1, -1));

        jDelete.setFont(new java.awt.Font("Phetsarath OT", 0, 11)); // NOI18N
        jDelete.setText("Delete");
        jDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, -1, -1));

        jTable_student.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_studentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_student);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 780, 410));

        jID_Student.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        jID_Student.setText("ລະຫັດນັກຮຽນ :");
        jPanel1.add(jID_Student, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 26));

        jB.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        jB.setText("ບ້ານ:");
        jPanel1.add(jB, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        jDt.setFont(new java.awt.Font("Phetsarath OT", 0, 11)); // NOI18N
        jPanel1.add(jDt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 160, -1));

        jID_Class.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        jID_Class.setText("ຫ້ອງຮຽນ : ");
        jPanel1.add(jID_Class, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        jPama.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        jPama.setText("ຜຸ້ປົກຄອງ : ");
        jPanel1.add(jPama, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        jpassword1.setFont(new java.awt.Font("Phetsarath OT", 0, 11)); // NOI18N
        jpassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpassword1ActionPerformed(evt);
            }
        });
        jPanel1.add(jpassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 120, -1));

        search.setFont(new java.awt.Font("Phetsarath OT", 0, 11)); // NOI18N
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 530, 700, -1));

        jLname.setFont(new java.awt.Font("Phetsarath OT", 0, 11)); // NOI18N
        jLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLnameActionPerformed(evt);
            }
        });
        jPanel1.add(jLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 190, -1));

        jVillage.setFont(new java.awt.Font("Phetsarath OT", 0, 11)); // NOI18N
        jPanel1.add(jVillage, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 160, -1));

        jprovine.setFont(new java.awt.Font("Phetsarath OT", 0, 11)); // NOI18N
        jPanel1.add(jprovine, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 180, -1));

        jlevel.setFont(new java.awt.Font("Phetsarath OT", 0, 11)); // NOI18N
        jlevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlevelActionPerformed(evt);
            }
        });
        jPanel1.add(jlevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 190, -1));

        jparent.setFont(new java.awt.Font("Phetsarath OT", 0, 11)); // NOI18N
        jPanel1.add(jparent, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 170, -1));

        jLabel1.setFont(new java.awt.Font("Defago Noto Sans", 1, 24)); // NOI18N
        jLabel1.setText("ເພີ່ມລາຍຊື່ນັກຮຽນ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Defago Noto Sans", 1, 24)); // NOI18N
        jLabel2.setText("ລາຍຊື່ນັກຮຽນທັງໝົດ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, -1, -1));

        Fname1.setFont(new java.awt.Font("Phetsarath OT", 0, 11)); // NOI18N
        Fname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fname1ActionPerformed(evt);
            }
        });
        jPanel1.add(Fname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 190, -1));

        jButton1.setText("search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 530, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 60, 620));
        jPanel1.add(jDateChoose, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 140, 30));

        jLabel3.setFont(new java.awt.Font("Defago Noto Sans", 1, 18)); // NOI18N
        jLabel3.setText("ປ້ອນຊື່ເພື່ອຄົ້ນຫາ:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 490, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1470, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlevelActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jlevelActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
          
    }//GEN-LAST:event_searchActionPerformed

    private void jDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteActionPerformed
        // TODO add your handling code here:
        try{
        int id = Integer.parseInt(jpassword1.getText());
        Student.deleteQuery(id);
        Tb_student("");
        }catch(NumberFormatException ex){
            System.out.println(ex.getMessage());
        }
        jpassword1.setText("");
        Fname1.setText("");
        jLname.setText("");
        jDateChoose.setDate(null);
        jVillage.setText("");
        jDt.setText("");
        jprovine.setText("");
        jlevel.setText("");
        jparent.setText("");

    }//GEN-LAST:event_jDeleteActionPerformed

    private void jCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelActionPerformed
        // TODO add your handling code here:
       this.dispose();
        
        

    }//GEN-LAST:event_jCancelActionPerformed

    private void jOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOKActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String B_date = dateFormat.format(jDateChoose.getDate());
        int pw = Integer.parseInt(jpassword1.getText());
        String Fname = Fname1.getText();
        String Lname = jLname.getText();
       
        String Vl = jVillage.getText();
        String M = jDt.getText();
        String Pv = jprovine.getText();
        String Lv = jlevel.getText();
        String Pl = jparent.getText();
        Student.addStudent(pw, Fname, Lname, B_date, Vl, M, Pv, Lv, Pl);
        
        Tb_student("");
    }//GEN-LAST:event_jOKActionPerformed

    private void jpassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpassword1ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jpassword1ActionPerformed

    private void jLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLnameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLnameActionPerformed

    private void jTable_studentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_studentMouseClicked
        // TODO add your handling code here:
        int index = jTable_student.getSelectedRow();
        String id = jTable_student.getValueAt(index, 0).toString();
        String Fname = jTable_student.getValueAt(index, 1).toString();
        String Lname = jTable_student.getValueAt(index, 2).toString();
        String DB = jTable_student.getValueAt(index, 3).toString();
        String Village = jTable_student.getValueAt(index, 4).toString();
        String District = jTable_student.getValueAt(index, 5).toString();
        String Provine = jTable_student.getValueAt(index, 6).toString();
        String Level = jTable_student.getValueAt(index, 7).toString();
        String Parent = jTable_student.getValueAt(index, 8).toString();
        Date b_date = null;
        try {
            b_date = new SimpleDateFormat("yyyy-MM-dd").parse(DB);
        } catch (ParseException ex) {
            System.out.println(ex.getMessage());
        }
        
        jpassword1.setText(id);
        search.setText(Fname);
        jLname.setText(Lname);
        jDateChoose.setDate(b_date);
        jVillage.setText(Village);
        jDt.setText(District);
        jprovine.setText(Provine);
        jlevel.setText(Level);
        jparent.setText(Parent);
        
    }//GEN-LAST:event_jTable_studentMouseClicked

    private void Fname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Fname1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name = search.getText();
        String searchQuery = "select * from Student where Fname ='"+name+"'";
        Tb_student(searchQuery);
        
    }//GEN-LAST:event_jButton1ActionPerformed

        public void Tb_student(String searchQuery){
        ArrayList<Student> datalist = Student.STUDENTList(searchQuery);
        
        String[] colNames = {"ID", "firstName", "Lastname", "Date of birth", "village", "district", "province","Level", "parent"};
        
        Object[][] Rows = new Object[datalist.size()][colNames.length];
        
        for(int i = 0; i<datalist.size(); i++)
        {
            Rows[i][0] = datalist.get(i).getJpassword();
            Rows[i][1] = datalist.get(i).getjFname();
            Rows[i][2] = datalist.get(i).getjLname();
            Rows[i][3] = datalist.get(i).getjDateBD();
            Rows[i][4] = datalist.get(i).getjVillage();
            Rows[i][5] = datalist.get(i).getjDt();
            Rows[i][6] = datalist.get(i).getJprovine();
            Rows[i][7] = datalist.get(i).getJlevel();
            Rows[i][8] = datalist.get(i).getJparent();
        }
        
        DefaultTableModel model = new DefaultTableModel(Rows, colNames);
        jTable_student.setModel(model);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                 if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interface1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interface1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interface1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interface1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interface1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Fname1;
    private javax.swing.JLabel jB;
    private javax.swing.JLabel jBD1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jCancel;
    private com.toedter.calendar.JDateChooser jDateChoose;
    private javax.swing.JButton jDelete;
    private javax.swing.JTextField jDt;
    private javax.swing.JLabel jFN;
    private javax.swing.JLabel jID_Class;
    private javax.swing.JLabel jID_Student;
    private javax.swing.JLabel jLN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jLname;
    private javax.swing.JLabel jM;
    private javax.swing.JButton jOK;
    private javax.swing.JLabel jPama;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jPv;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_student;
    private javax.swing.JTextField jVillage;
    private javax.swing.JTextField jlevel;
    private javax.swing.JTextField jparent;
    private javax.swing.JTextField jpassword1;
    private javax.swing.JTextField jprovine;
    private javax.swing.JTextField search;
    // End of variables declaration//GEN-END:variables
}
